version: "3.5"
services:
  mongo-express:
    image: mongo-express:latest
    container_name: go-grpc-ecomm-mongo-express
    restart: unless-stopped
    env_file: ../../.env
    environment:
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: $MONGO_USERNAME
      ME_CONFIG_MONGODB_ADMINPASSWORD: $MONGO_PASSWORD
      ME_CONFIG_BASICAUTH_USERNAME: $MONGO_USERNAME
      ME_CONFIG_BASICAUTH_PASSWORD: $MONGO_PASSWORD
    ports:
      - 8081:8081
    networks:
      - go-grpc-ecomm
  mongo:
    image: mongo:latest
    container_name: go-grpc-ecomm-mongo
    restart: unless-stopped
    env_file: ../../.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASSWORD
      MONGO_INITDB_DATABASE: $MONGO_DB
    ports:
      - 27017:27017
    expose:
      - 27017
    volumes:
      - dbdata:/data/db
      - ../../init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
    networks:
      - go-grpc-ecomm
networks:
  go-grpc-ecomm:
    external:
      name: go_grpc_ecomm
volumes:
  dbdata:
